# Generated by Django 4.0.3 on 2022-04-18 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addNewScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieScreenName', models.CharField(max_length=300)),
                ('movieScreen', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('movieScreenSeatCapacity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.UUIDField(default=uuid.uuid4)),
                ('accountPassword', models.UUIDField(default=uuid.uuid4)),
                ('firstname', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField(max_length=8)),
                ('street', models.CharField(max_length=300)),
                ('streetnumber', models.CharField(max_length=300)),
                ('cr_city', models.CharField(max_length=300)),
                ('cr_postcode', models.CharField(max_length=300)),
                ('cr_email', models.EmailField(max_length=254)),
                ('cr_landline', models.IntegerField()),
                ('cr_mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='movieListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=300)),
                ('movieDescription', models.CharField(max_length=300)),
                ('movieRunTimeMinutes', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('movieRating', models.CharField(choices=[('Universal', 'U'), ('Parental Guidance', 'PG'), ('12 Guidance ', '12A'), ('12 And Over ', '12'), ('15 and Over', '15'), ('18 and over', '18'), ('18 Special', '18R')], default='Universal', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='movieTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTime', models.DateTimeField()),
                ('movieDate', models.DateField()),
                ('movieDesired', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MovieManaging.movielisting')),
                ('movieScreen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MovieManaging.addnewscreen')),
            ],
        ),
        migrations.CreateModel(
            name='pickUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('movie Manager', 'Movie Manager'), ('Club Rep', 'Club Rep')], default='Admin', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pickMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTime', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MovieManaging.movietimeslots')),
                ('movieTitle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MovieManaging.movielisting')),
            ],
        ),
    ]
