# Generated by Django 3.2.13 on 2022-05-04 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManaging', '0004_pickmovie_cancelrequested'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielisting',
            name='movieImage',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movietimeslots',
            name='movieDesired',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieManaging.movielisting'),
        ),
        migrations.AlterField(
            model_name='movietimeslots',
            name='movieScreen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieManaging.addnewscreen'),
        ),
    ]
