# Generated by Django 3.2.13 on 2022-05-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManaging', '0005_auto_20220504_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickmovie',
            name='customerEmail',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
