# Generated by Django 4.0.3 on 2022-05-01 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('streetNum', models.IntegerField()),
                ('city', models.CharField(max_length=300)),
                ('postcode', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('landline', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.UUIDField(default=uuid.uuid4)),
                ('accountPassword', models.UUIDField(default=uuid.uuid4)),
                ('firstname', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField(max_length=8)),
                ('accountEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='studentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.UUIDField(default=uuid.uuid4)),
                ('accountTitle', models.CharField(max_length=300)),
                ('discountRate', models.CharField(max_length=300)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.clubdetails')),
            ],
        ),
        migrations.CreateModel(
            name='discountList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newDiscountRate', models.CharField(max_length=300)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.studentclub')),
            ],
        ),
    ]
