# Generated by Django 4.0.3 on 2022-04-18 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.UUIDField(default=uuid.uuid4)),
                ('accountTitle', models.CharField(max_length=300)),
                ('discountRate', models.CharField(max_length=300)),
            ],
        ),
    ]
