# Generated by Django 4.0.3 on 2022-04-18 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('streetNum', models.IntegerField()),
                ('cr_city', models.CharField(max_length=300)),
                ('cr_postcode', models.CharField(max_length=300)),
                ('cr_email', models.EmailField(max_length=254)),
                ('cr_landline', models.IntegerField()),
                ('cr_mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.UUIDField(default=uuid.uuid4)),
                ('accountPassword', models.UUIDField(default=uuid.uuid4)),
                ('firstname', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField(max_length=8)),
            ],
        ),
    ]
