# Generated by Django 3.2.13 on 2022-05-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clubrep_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetails',
            name='clubName',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
