# Generated by Django 4.0.3 on 2022-04-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentclub_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubdetails',
            old_name='cr_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='clubdetails',
            old_name='cr_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clubdetails',
            old_name='cr_landline',
            new_name='landline',
        ),
        migrations.RenameField(
            model_name='clubdetails',
            old_name='cr_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='clubdetails',
            old_name='cr_postcode',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='studentclub',
            name='club',
        ),
    ]
