# Generated by Django 4.0.3 on 2022-05-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentclub_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='discountList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newDiscountRate', models.CharField(max_length=300)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.studentclub')),
            ],
        ),
    ]
